### ISSUE TITLE
Stackblitz link

### ISSUE THREAD

**Issue by EngelschallNikolaus** [rstropek-teaching/turmrechnen-quiz-4ahif-EngelschallNikolaus#1]
Dear Mr. Stropek,

here is my link for the solution on Stackblitz:
https://angular-rpzty5.stackblitz.io/

Greetings, Nikolaus Engelschall

**Comment by rstropek** [comment]
Nearly. Two issues:

* *Calculate* not disabled if *height* is invalid
* Result is not a table

Greetings,
Rainer Stropek.

**Comment by EngelschallNikolaus** [comment]
Thank you for your fast feedback.
I've changed my program so that it should work fine now.

Greetings, Nikolaus Engelschall

**Comment by rstropek** [comment]
Well done, extra point is secured.
